-- 00_schema_and_seed_data.sql
-- Creates the aaa_roadside database and the roadside_requests table
-- aligned with the synthetic generator output. Then loads the CSV.

DROP DATABASE IF EXISTS aaa_roadside;
CREATE DATABASE aaa_roadside;
USE aaa_roadside;

DROP TABLE IF EXISTS roadside_requests;

CREATE TABLE roadside_requests (
    request_id        BIGINT PRIMARY KEY,
    member_id         BIGINT NOT NULL,

    request_ts        DATETIME NOT NULL,
    dispatch_ts       DATETIME NOT NULL,
    arrival_ts        DATETIME NOT NULL,
    completion_ts     DATETIME NOT NULL,

    latitude          DECIMAL(9,6),
    longitude         DECIMAL(9,6),

    zip_code          VARCHAR(10),
    city              VARCHAR(100),
    state             CHAR(2),

    road_type         VARCHAR(20),
    issue_type        VARCHAR(50),

    truck_id          INT,
    vin               VARCHAR(50),

    miles_towed       DECIMAL(6,1),
    call_source       VARCHAR(20),

    membership_start  DATETIME,
    member_home_zip   VARCHAR(10)
);

-- -------------------------------------------------------------------
-- OPTIONAL: bulk load from CSV generated by Synthetic_Roadside.py
-- Make sure the CSV (synthetic_roadside_requests.csv) is placed in:
--     C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/
-- or wherever secure_file_priv points.
-- -------------------------------------------------------------------

-- SHOW VARIABLES LIKE 'secure_file_priv';

-- LOAD DATA INFILE '/path/to/synthetic_roadside_requests.csv'
-- INTO TABLE roadside_requests
-- FIELDS TERMINATED BY ',' 
-- ENCLOSED BY '"'
-- LINES TERMINATED BY '\n'
-- IGNORE 1 ROWS (
--     request_id,
--     member_id,
--     request_ts,
--     dispatch_ts,
--     arrival_ts,
--     completion_ts,
--     latitude,
--     longitude,
--     zip_code,
--     city,
--     state,
--     road_type,
--     issue_type,
--     truck_id,
--     vin,
--     miles_towed,
--     call_source,
--     membership_start,
--     member_home_zip
-- );
